### ISSUE TITLE
Contabo VPS

### ISSUE THREAD

**Issue by kintaro1981** [eric-pierce/Personal-Cloud#2]
Hello,
I’m reading that you are using Contabo VPS with 400GB SSD.

I saw many complains about Contabo’s reliability, especially with their SSD.

What’s your experience with it?

**Comment by eric-pierce** [comment]
@kintaro1981 I've had nothing but positive experiences with Contabo - I actually run two VPS instances with them and in the several years they've been running there was one unexpected outage which lasted around 20 minutes. I haven't shopped around recently so I can't speak to the value, but part of the reason I haven't been looking for alternatives is that they've checked all the boxes I need them to.
